* Sitio con material complementario del _libro Estadística Aplicada e Inferencial_

En este repositorio se almacenan los scripts de [[https://devtools.r-lib.org/][R]] de los ejercicios estipulados en el libro *Estadística Aplicada e Inferencial* del Profesor [[https://eljatib.com][Christian Salas-Eljatib]] del [[https://biometriaforestal.uchile.cl][Laboratorio de Biometría y Modelación Forestal]] y del [[https://www.postgradofen.uchile.cl/mag%C3%ADster-en-pol%C3%ADticas-p%C3%BAblicas-escuela-de-postgrado-facultad-de-econom%C3%ADa-y-negocios-universidad-de-chile][Magíster en Políticas Públicas]] de la [[https://uchile.cl][Universidad de Chile]].


*** I. Paquetes de R
Para el correcto uso de los scripts, es necesario tener instalados los paquetes =datana= y =biometrics= en su versión de R. 

Por lo tanto, debe primero proceder como sigue

  #+begin_src R
  install.packages("datana")
  install.packages("biometrics") 
  #+end_src
  
 Para *verificar* que ambos paquetes estan correctamente instalados, ejecute:

  #+begin_src R
  library(datana)
  library(biometrics)
  #+end_src
y para verificar la versión del paquete, puede emplear la función =packageVersion()= como sigue
#+begin_src R
packageVersion("datana")
#+end_src

Cita del paquete
#+begin_src R
citation("datana")
#+end_src

**** Versiones más actualizadas de los paquetes 
Es importante destacar que las versiones más recientes de los paquetes antes mencionados se encuentran en el siguiente 
[[https://github.com/cseljatib/labPackages][web]], para vuestra descarga. Esto se debe a que la frecuencia con la cual se puede
actualizar un paquete en [[https://r-project.or][el sitio web de R]] es generalmente menor a la cual nosotros realizamos cambios.

*** II. Flujo de los scripts
Los scripts son presentados siguiendo un sentido docente.
**** Inferencia

1. phipotesis.r: tiene solo comparacion con valor t-tabulado
   
2. phipovalorp.r: explica ademas al valor-p
   
3. phipointconf.r: relaciona intervalo de confianza con prueba de hipotesis (no valor-P)
   
4. phipotesisf.r: version full, relaciona intervalo de confianza con prueba de hipotesis y valor-P

*** III. Sugerencias/errores
En caso de encontrar errores, tenga sugerencias, o dudas, por favor escribir a [[mailto:christian.salas@uchile.cl][este email]].

